export const API_ROUTE = '/api'
export const TASKS_ROUTE = '/tasks'
export const AUTH_ROUTE = '/auth'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const NEW_ROUTE = '/new'
export const FORGOT_PASSWORD_RESET_ROUTE = '/forgot-password-request'
export const PASSWORD_RESET_ROUTE = '/reset-password'

export const USER_ID_KEY = 'userId'